export const BNSF_STATIONS = [
    "Union Station",
    "Halsted",
    "Western Avenue",
    "Cicero",
    "LaVergne",
    "Berwyn",
    "Harlem Avenue",
    "Riverside",
    "Hollywood",
    "Brookfield",
    "Congress Park",
    "LaGrange Road",
    "LaGrange Stone Avenue",
    "Western Springs",
    "Highlands",
    "Hinsdale",
    "West Hinsdale",
    "Clarendon Hills",
    "Westmont",
    "Fairview Avenue",
    "Downers Grove Main Street",
    "Belmont",
    "Lisle",
    "Naperville",
    "Route 59",
    "Aurora",
];

export const HC_STATIONS = [
    "Union Station",
    "Summit",
    "Willow Springs",
    "Lemont",
    "Romeoville",
    "Lockport",
    "Joliet",
];

export const ME_STATIONS = [
    "Millennium Station",
    "Van Buren Street",
    "Museum Campus / 11th Street",
    "18th Street",
    "McCormick Place",
    "27th Street",
    "47th St Kenwood",
    "51st/53rd St Hyde Park",
    "55th - 56th - 57th Street",
    "59th St, University of Chicago",
    "63rd Street",
    "75th Street Grand Crossing",
    "79th St/Chatham",
    "83rd Street Avalon Park",
    "87th Street/Woodruff",
    "91st Street Chesterfield",
    "95th St Chicago State University",
    "103rd St Rosemoor",
    "107th Street",
    "111th St Pullman",
    "Kensington / 115th Street",
    "Riverdale",
    "Ivanhoe",
    "147th St Sibley",
    "Harvey",
    "Hazel Crest",
    "Calumet",
    "Homewood",
    "Flossmoor",
    "Olympia Fields",
    "211th Street",
    "Matteson",
    "Richton Park",
    "University Park",
    "Stony Island",
    "Bryn Mawr",
    "South Shore",
    "Windsor Park",
    "79th Street",
    "83rd St",
    "87th St",
    "93rd St",
    "State Street",
    "Stewart Ridge",
    "West Pullman",
    "Racine",
    "Ashland",
    "Burr Oak",
    "Blue Island",
];

export const MDN_STATIONS = [
    "Union Station",
    "Western Avenue",
    "Healy",
    "Grayland",
    "Mayfair",
    "Forest Glen",
    "Edgebrook",
    "Morton Grove",
    "Golf",
    "Glenview",
    "Glen of North Glenview",
    "Northbrook",
    "Lake Cook Road",
    "Deerfield",
    "Lake Forest",
    "Libertyville",
    "Prairie Crossing / Libertyville",
    "Grayslake",
    "Round Lake",
    "Long Lake",
    "Ingleside",
    "Fox Lake",
];

export const MDW_STATIONS = [
    "Union Station",
    "Western Avenue",
    "Grand / Cicero",
    "Hanson Park",
    "Galewood",
    "Mars",
    "Mont Clare",
    "Elmwood Park",
    "River Grove",
    "Franklin Park",
    "Mannheim",
    "Bensenville",
    "Wood Dale",
    "Itasca",
    "Medinah",
    "Roselle",
    "Schaumburg",
    "Hanover Park",
    "Bartlett",
    "National Street",
    "Elgin",
    "Big Timber Road",
];

export const NCS_STATIONS = [
    "Union Station",
    "Western Avenue",
    "River Grove",
    "Belmont Ave / Franklin Park",
    "Schiller Park",
    "Rosemont",
    "O'Hare Transfer",
    "Prospect Heights",
    "Wheeling",
    "Buffalo Grove",
    "Prairie View",
    "Vernon Hills",
    "Mundelein",
    "Prairie Crossing / Libertyville",
    "Washington St / Grayslake",
    "Round Lake Beach",
    "Lake Villa",
    "Antioch",
];

export const RI_STATIONS = [
    "LaSalle Street Station",
    "35th St - Lou Jones",
    "Gresham",
    "95th St - Longwood",
    "103rd St - Washington Hts",
    "Brainerd",
    "Beverly Hills - 91st Street",
    "Beverly Hills - 95th Street",
    "Beverly Hills - 99th Street",
    "Beverly Hills - 107th Street",
    "Morgan Park - 111th Street",
    "Morgan Park - 115th Street",
    "119th Street",
    "123rd Street",
    "Prairie St",
    "Blue Island - Vermont St",
    "Robbins",
    "Midlothian",
    "Oak Forest",
    "Tinley Park",
    "Tinley Park - 80th Ave",
    "Hickory Creek",
    "Mokena",
    "New Lenox",
    "Joliet",
];

export const SWS_STATIONS = [
    "Union Station",
    "Wrightwood",
    "Ashburn",
    "Oak Lawn Patriot Station",
    "Chicago Ridge",
    "Worth",
    "Palos Heights",
    "Palos Park",
    "Orland Park 143rd Street",
    "Orland Park 153rd Street",
    "Orland Park 179th Street",
    "New Lenox Laraway Road",
    "Manhattan",
];

export const UPN_STATIONS = [
    "Ogilvie Transportation Center",
    "Clybourn",
    "Ravenswood",
    "Peterson / Ridge",
    "Rogers Park",
    "Evanston Main Street",
    "Evanston Davis Street",
    "Evanston Central Street",
    "Wilmette",
    "Kenilworth",
    "Indian Hill",
    "Winnetka",
    "Hubbard Woods",
    "Glencoe",
    "Braeside",
    "Ravinia Park",
    "Ravinia",
    "Highland Park",
    "Highwood",
    "Fort Sheridan",
    "Lake Forest",
    "Lake Bluff",
    "Great Lakes",
    "North Chicago",
    "Waukegan",
    "Zion",
    "Winthrop Harbor",
    "Kenosha",
];

export const UPNW_STATIONS = [
    "Ogilvie Transportation Center",
    "Clybourn",
    "Irving Park",
    "Jefferson Park",
    "Gladstone Park",
    "Norwood Park",
    "Edison Park",
    "Park Ridge",
    "Dee Road",
    "Des Plaines",
    "Cumberland",
    "Mount Prospect",
    "Arlington Heights",
    "Arlington Park",
    "Palatine",
    "Barrington",
    "Fox River Grove",
    "Cary",
    "Pingree Road",
    "Crystal Lake",
    "Woodstock",
    "McHenry",
    "Harvard",
];

export const UPW_STATIONS = [
    "Ogilvie Transportation Center",
    "Kedzie",
    "Oak Park",
    "River Forest",
    "Maywood",
    "Melrose Park",
    "Bellwood",
    "Berkeley",
    "Elmhurst",
    "Villa Park",
    "Lombard",
    "Glen Ellyn",
    "College Avenue",
    "Wheaton",
    "Winfield",
    "West Chicago",
    "Geneva",
    "La Fox",
    "Elburn",
];
